### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by emireko** [bradenhurl/DeepGTAV-PreSIL#12]
Hi all,

In **dataset.py** I get the error below.

**Trying to connect to DeepGTAV
ERROR: Failed to connect to DeepGTAV
Connecting to client...
ERROR: Failed to send message. Reason: [WinError 10057]**

Any help would be appreciated.

**Comment by bradenhurl** [comment]
Is GTAV started with the DeepGTAV plugin? Can you check the logs in your GTAV folder to see that the plugin has started?

**Comment by Sudo42b** [comment]
please check to width and height your .py code

**Comment by LEE-SEON-WOO** [comment]
Fixes #

**Comment by makaveli10** [comment]
@bradenhurl I am seeing the same error:
```
python3 dataset
Trying to connect to DeepGTAV
ERROR: Failed to connect to DeepGTAV
Connecting to client...
ERROR: Failed to send message. Reason: [Errno 32] Broken pipe
Message sent to client to begin.
Traceback (most recent call last):
  File "dataset", line 188, in <module>
    message = client.recvMessage()  
  File "/home/marcus/vineet-workspace/DeepGTAV-PreSIL/VPilot/deepgtav/client.py", line 52, in recvMessage
    frame = self._recvall()
  File "/home/marcus/vineet-workspace/DeepGTAV-PreSIL/VPilot/deepgtav/client.py", line 66, in _recvall
    packet = self.s.recv(4 - len(data))
OSError: [Errno 107] Transport endpoint is not connected

```

**Comment by lvbu2025** [comment]
I have a problem also at line 189 but could be related.

`Trying to connect to DeepGTAV                                                                                           Successfully connected to DeepGTAV                                                                                      Connecting to client...                                                                                                 Message sent to client to begin.                                                                                        ERROR: Failed to receive frame                                                                                          Traceback (most recent call last):                                                                                        File "dataset", line 189, in <module>                                                                                     index = message['index']                                                                                            TypeError: 'NoneType' object is not subscriptable `

**Comment by SoraKoubou** [comment]
> I have a problem also at line 189 but could be related.
> 
> `Trying to connect to DeepGTAV Successfully connected to DeepGTAV Connecting to client... Message sent to client to begin. ERROR: Failed to receive frame Traceback (most recent call last): File "dataset", line 189, in <module> index = message['index'] TypeError: 'NoneType' object is not subscriptable `

Hello, I have the same problem as you. Have you solved it? Thank you very much!
